name: Build and deploy Thuc Tran's blog to Azure App Services on LiNuX

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Nodejs version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: npm install, build (and test)
        run: |
        npm install
        npm run build --if-present
      - name: zip all files for upload between jobs
        run: zip --symlinks -r nest.zip ./*
      - name: upload artifact for deploy job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: nest.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: $

    steps:
      - name: download artifact afrom build jobs
        uses: actions/download-artifact@v2
        with:
          name: node-app
      - name: deploy to web app
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sampleapp'
          slot-name: 'Production'
          publish-profile: $
          package: nest.zip
      - name: delete zip file
        run: rm nest.zip
